// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: PrinterScreen

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_screenLoading
void ui_screenLoading_screen_init(void);
lv_obj_t *ui_screenLoading;
lv_obj_t *ui_imgWifi;
lv_obj_t *ui_imgMosquitto;
lv_obj_t *ui_barLoading;
lv_obj_t *ui_lblLoading;


// SCREEN: ui_screenMain
void ui_screenMain_screen_init(void);
lv_obj_t *ui_screenMain;
lv_obj_t *ui_tabMain;
lv_obj_t *ui_StatusTab;
lv_obj_t *ui_pnlTop;
lv_obj_t *ui_lblTopTitle;
lv_obj_t *ui_lblTopHumidity;
lv_obj_t *ui_lblTopTemp;
lv_obj_t *ui_chartPrusa;
lv_obj_t *ui_chartEnder;
lv_obj_t *ui_pnlBottom;
lv_obj_t *ui_lblBottomTitle;
lv_obj_t *ui_lblBottomHumidity;
lv_obj_t *ui_lblBottomTemp;
lv_obj_t *ui_SettingsTab;
lv_obj_t *ui_colorWheelPrusaLight;
lv_obj_t *ui_colorWheelEnderLight;
lv_obj_t *ui_lblEnderLightColor;
lv_obj_t *ui_lblPrusaLightColor;
lv_obj_t *ui_pnlStatus;
lv_obj_t *ui_lblTime;
lv_obj_t *ui_lblIpAddress;
lv_obj_t *ui_lblMosquitto;
lv_obj_t *ui_lblWifi;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_wifi_[1] = {&ui_img_wifi_1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_screenLoading_screen_init();
ui_screenMain_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_screenLoading);
}
