// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: PrinterScreen

#ifndef _PRINTERSCREEN_UI_H
#define _PRINTERSCREEN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include <lvgl.h>

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_screenLoading
void ui_screenLoading_screen_init(void);
extern lv_obj_t *ui_screenLoading;
extern lv_obj_t *ui_imgWifi;
extern lv_obj_t *ui_imgMosquitto;
extern lv_obj_t *ui_barLoading;
extern lv_obj_t *ui_lblLoading;
// SCREEN: ui_screenMain
void ui_screenMain_screen_init(void);
extern lv_obj_t *ui_screenMain;
extern lv_obj_t *ui_tabMain;
extern lv_obj_t *ui_StatusTab;
extern lv_obj_t *ui_pnlTop;
extern lv_obj_t *ui_lblTopTitle;
extern lv_obj_t *ui_lblTopHumidity;
extern lv_obj_t *ui_lblTopTemp;
extern lv_obj_t *ui_chartPrusa;
extern lv_obj_t *ui_chartEnder;
extern lv_obj_t *ui_pnlBottom;
extern lv_obj_t *ui_lblBottomTitle;
extern lv_obj_t *ui_lblBottomHumidity;
extern lv_obj_t *ui_lblBottomTemp;
extern lv_obj_t *ui_SettingsTab;
extern lv_obj_t *ui_colorWheelPrusaLight;
extern lv_obj_t *ui_colorWheelEnderLight;
extern lv_obj_t *ui_lblEnderLightColor;
extern lv_obj_t *ui_lblPrusaLightColor;
extern lv_obj_t *ui_pnlStatus;
extern lv_obj_t *ui_lblTime;
extern lv_obj_t *ui_lblIpAddress;
extern lv_obj_t *ui_lblMosquitto;
extern lv_obj_t *ui_lblWifi;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_wifi_1_png);   // assets/wifi_1.png
LV_IMG_DECLARE( ui_img_mqtt_grey_png);   // assets/mqtt_grey.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
