// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: PrinterScreen

#include "../ui.h"

void ui_screenScreenSaver_screen_init(void)
{
ui_screenScreenSaver = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenScreenSaver, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_spinSaver = lv_spinner_create(ui_screenScreenSaver,6000,90);
lv_obj_set_width( ui_spinSaver, 20);
lv_obj_set_height( ui_spinSaver, 20);
lv_obj_set_align( ui_spinSaver, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_spinSaver, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_width(ui_spinSaver, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_spinSaver, lv_color_hex(0xFF8D00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_spinSaver, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_spinSaver, 30, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_screenScreenSaver, ui_event_screenScreenSaver, LV_EVENT_ALL, NULL);

}
