// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: PrinterScreen

#include "../ui.h"

void ui_screenLoading_screen_init(void)
{
ui_screenLoading = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenLoading, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgWifi = lv_img_create(ui_screenLoading);
lv_img_set_src(ui_imgWifi, &ui_img_wifi_1_png);
lv_obj_set_width( ui_imgWifi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_imgWifi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_imgWifi, 0 );
lv_obj_set_y( ui_imgWifi, -60 );
lv_obj_set_align( ui_imgWifi, LV_ALIGN_CENTER );
lv_obj_add_state( ui_imgWifi, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_imgWifi, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgWifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgSystem = lv_img_create(ui_screenLoading);
lv_img_set_src(ui_imgSystem, &ui_img_gear_grey_png);
lv_obj_set_width( ui_imgSystem, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_imgSystem, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_imgSystem, -181 );
lv_obj_set_y( ui_imgSystem, -60 );
lv_obj_set_align( ui_imgSystem, LV_ALIGN_CENTER );
lv_obj_add_state( ui_imgSystem, LV_STATE_USER_1 );     /// States
lv_obj_add_flag( ui_imgSystem, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgSystem, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgMosquitto = lv_img_create(ui_screenLoading);
lv_img_set_src(ui_imgMosquitto, &ui_img_mqtt_grey_png);
lv_obj_set_width( ui_imgMosquitto, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_imgMosquitto, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_imgMosquitto, 181 );
lv_obj_set_y( ui_imgMosquitto, -55 );
lv_obj_set_align( ui_imgMosquitto, LV_ALIGN_CENTER );
lv_obj_add_state( ui_imgMosquitto, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_imgMosquitto, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgMosquitto, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_barLoading = lv_bar_create(ui_screenLoading);
lv_bar_set_value(ui_barLoading,15,LV_ANIM_OFF);
lv_obj_set_width( ui_barLoading, 200);
lv_obj_set_height( ui_barLoading, 25);
lv_obj_set_x( ui_barLoading, 0 );
lv_obj_set_y( ui_barLoading, 60 );
lv_obj_set_align( ui_barLoading, LV_ALIGN_CENTER );

ui_lblLoading = lv_label_create(ui_screenLoading);
lv_obj_set_width( ui_lblLoading, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblLoading, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblLoading, 0 );
lv_obj_set_y( ui_lblLoading, 130 );
lv_obj_set_align( ui_lblLoading, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblLoading,"Initializing..");
lv_obj_set_style_text_font(ui_lblLoading, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_imgWifi, ui_event_imgWifi, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_imgMosquitto, ui_event_imgMosquitto, LV_EVENT_ALL, NULL);

}
