// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: PrinterScreen

#include "../ui.h"

void ui_screenMain_screen_init(void)
{
ui_screenMain = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenMain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_tabMain = lv_tabview_create(ui_screenMain, LV_DIR_BOTTOM, 50);
lv_obj_set_width( ui_tabMain, 800);
lv_obj_set_height( ui_tabMain, 480);
lv_obj_set_x( ui_tabMain, -1 );
lv_obj_set_y( ui_tabMain, 0 );
lv_obj_set_align( ui_tabMain, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_tabMain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_StatusTab = lv_tabview_add_tab(ui_tabMain, "Status");
lv_obj_clear_flag( ui_StatusTab, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_StatusTab, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StatusTab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnPrusaLight = lv_imgbtn_create(ui_StatusTab);
lv_imgbtn_set_src(ui_btnPrusaLight, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_light_on_png, NULL);
lv_imgbtn_set_src(ui_btnPrusaLight, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_light_on_png, NULL);
lv_obj_set_height( ui_btnPrusaLight, 50);
lv_obj_set_width( ui_btnPrusaLight, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_btnPrusaLight, -40 );
lv_obj_set_y( ui_btnPrusaLight, -135 );
lv_obj_set_align( ui_btnPrusaLight, LV_ALIGN_CENTER );

ui_btnEnderLight = lv_imgbtn_create(ui_StatusTab);
lv_imgbtn_set_src(ui_btnEnderLight, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_light_white_png, NULL);
lv_imgbtn_set_src(ui_btnEnderLight, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_light_on_png, NULL);
lv_obj_set_height( ui_btnEnderLight, 50);
lv_obj_set_width( ui_btnEnderLight, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_btnEnderLight, -35 );
lv_obj_set_y( ui_btnEnderLight, 55 );
lv_obj_set_align( ui_btnEnderLight, LV_ALIGN_CENTER );

ui_chartPrusa = lv_chart_create(ui_StatusTab);
lv_obj_set_width( ui_chartPrusa, 200);
lv_obj_set_height( ui_chartPrusa, 100);
lv_obj_set_x( ui_chartPrusa, 239 );
lv_obj_set_y( ui_chartPrusa, -90 );
lv_obj_set_align( ui_chartPrusa, LV_ALIGN_CENTER );
lv_chart_set_type( ui_chartPrusa, LV_CHART_TYPE_LINE);
lv_chart_set_range( ui_chartPrusa, LV_CHART_AXIS_PRIMARY_Y, 25, 125);
lv_chart_set_range( ui_chartPrusa, LV_CHART_AXIS_SECONDARY_Y, 25, 125);
lv_chart_set_axis_tick( ui_chartPrusa, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_chartPrusa, LV_CHART_AXIS_PRIMARY_Y, 0, 5, 0, 2, true, 50);
lv_chart_set_axis_tick( ui_chartPrusa, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
lv_chart_series_t* ui_chartPrusa_series_1 = lv_chart_add_series(ui_chartPrusa, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_chartPrusa_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_chartPrusa, ui_chartPrusa_series_1, ui_chartPrusa_series_1_array);
lv_chart_series_t* ui_chartPrusa_series_2 = lv_chart_add_series(ui_chartPrusa, lv_color_hex(0xFF0000), LV_CHART_AXIS_SECONDARY_Y);
static lv_coord_t ui_chartPrusa_series_2_array[] = { 100,80,95,88,110,75,50,80,99,102 };
lv_chart_set_ext_y_array(ui_chartPrusa, ui_chartPrusa_series_2, ui_chartPrusa_series_2_array);



ui_lblPrusaTemp = lv_label_create(ui_StatusTab);
lv_obj_set_width( ui_lblPrusaTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblPrusaTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblPrusaTemp, -130 );
lv_obj_set_y( ui_lblPrusaTemp, -133 );
lv_obj_set_align( ui_lblPrusaTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblPrusaTemp,"100");
lv_obj_set_style_text_font(ui_lblPrusaTemp, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblEnderTemp = lv_label_create(ui_StatusTab);
lv_obj_set_width( ui_lblEnderTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblEnderTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblEnderTemp, -123 );
lv_obj_set_y( ui_lblEnderTemp, 53 );
lv_obj_set_align( ui_lblEnderTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblEnderTemp,"98");
lv_obj_set_style_text_font(ui_lblEnderTemp, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_chartEnder = lv_chart_create(ui_StatusTab);
lv_obj_set_width( ui_chartEnder, 200);
lv_obj_set_height( ui_chartEnder, 100);
lv_obj_set_x( ui_chartEnder, 239 );
lv_obj_set_y( ui_chartEnder, 90 );
lv_obj_set_align( ui_chartEnder, LV_ALIGN_CENTER );
lv_chart_set_type( ui_chartEnder, LV_CHART_TYPE_LINE);
lv_chart_set_range( ui_chartEnder, LV_CHART_AXIS_SECONDARY_Y, 25, 125);
lv_chart_set_axis_tick( ui_chartEnder, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_chartEnder, LV_CHART_AXIS_PRIMARY_Y, 0, 5, 0, 2, false, 50);
lv_chart_set_axis_tick( ui_chartEnder, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
lv_chart_series_t* ui_chartEnder_series_1 = lv_chart_add_series(ui_chartEnder, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_chartEnder_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_chartEnder, ui_chartEnder_series_1, ui_chartEnder_series_1_array);
lv_chart_series_t* ui_chartEnder_series_2 = lv_chart_add_series(ui_chartEnder, lv_color_hex(0xE92323), LV_CHART_AXIS_SECONDARY_Y);
static lv_coord_t ui_chartEnder_series_2_array[] = { 100,80,95,88,110,75,50,80,99,102 };
lv_chart_set_ext_y_array(ui_chartEnder, ui_chartEnder_series_2, ui_chartEnder_series_2_array);



ui_btnPrusa = lv_imgbtn_create(ui_StatusTab);
lv_imgbtn_set_src(ui_btnPrusa, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_prusa2_png, NULL);
lv_imgbtn_set_src(ui_btnPrusa, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_prusa2_png, NULL);
lv_obj_set_width( ui_btnPrusa, 75);
lv_obj_set_height( ui_btnPrusa, 75);
lv_obj_set_x( ui_btnPrusa, -286 );
lv_obj_set_y( ui_btnPrusa, -80 );
lv_obj_set_align( ui_btnPrusa, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_btnPrusa, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_outline_color(ui_btnPrusa, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_btnPrusa, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_btnPrusa, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_btnPrusa, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_btnPrusa, lv_color_hex(0xE96A18), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_btnPrusa, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_btnPrusa, 4, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_btnPrusa, 2, LV_PART_MAIN| LV_STATE_PRESSED);

ui_btnEnder = lv_imgbtn_create(ui_StatusTab);
lv_imgbtn_set_src(ui_btnEnder, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_ender2_png, NULL);
lv_imgbtn_set_src(ui_btnEnder, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_ender2_png, NULL);
lv_obj_set_width( ui_btnEnder, 75);
lv_obj_set_height( ui_btnEnder, 75);
lv_obj_set_x( ui_btnEnder, -286 );
lv_obj_set_y( ui_btnEnder, 115 );
lv_obj_set_align( ui_btnEnder, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_btnEnder, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_outline_color(ui_btnEnder, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_btnEnder, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_btnEnder, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_btnEnder, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_btnEnder, lv_color_hex(0x201FD6), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_btnEnder, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_btnEnder, 4, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_btnEnder, 2, LV_PART_MAIN| LV_STATE_PRESSED);

ui_SettingsTab = lv_tabview_add_tab(ui_tabMain, "Settings");
lv_obj_clear_flag( ui_SettingsTab, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_colorWheelPrusaLight = lv_colorwheel_create(ui_SettingsTab,true);
lv_obj_set_width( ui_colorWheelPrusaLight, 150);
lv_obj_set_height( ui_colorWheelPrusaLight, 150);
lv_obj_set_x( ui_colorWheelPrusaLight, -183 );
lv_obj_set_y( ui_colorWheelPrusaLight, 0 );
lv_obj_set_align( ui_colorWheelPrusaLight, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_colorWheelPrusaLight, LV_OBJ_FLAG_GESTURE_BUBBLE );    /// Flags

ui_colorWheelEnderLight = lv_colorwheel_create(ui_SettingsTab,true);
lv_obj_set_width( ui_colorWheelEnderLight, 150);
lv_obj_set_height( ui_colorWheelEnderLight, 150);
lv_obj_set_x( ui_colorWheelEnderLight, 188 );
lv_obj_set_y( ui_colorWheelEnderLight, 0 );
lv_obj_set_align( ui_colorWheelEnderLight, LV_ALIGN_CENTER );

ui_lblEnderLightColor = lv_label_create(ui_SettingsTab);
lv_obj_set_width( ui_lblEnderLightColor, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblEnderLightColor, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblEnderLightColor, 183 );
lv_obj_set_y( ui_lblEnderLightColor, -124 );
lv_obj_set_align( ui_lblEnderLightColor, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblEnderLightColor,"Ender Light");

ui_lblPrusaLightColor = lv_label_create(ui_SettingsTab);
lv_obj_set_width( ui_lblPrusaLightColor, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblPrusaLightColor, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblPrusaLightColor, -183 );
lv_obj_set_y( ui_lblPrusaLightColor, -127 );
lv_obj_set_align( ui_lblPrusaLightColor, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblPrusaLightColor,"Prusa Light");

ui_pnlStatus = lv_obj_create(ui_screenMain);
lv_obj_set_height( ui_pnlStatus, 30);
lv_obj_set_width( ui_pnlStatus, lv_pct(100));
lv_obj_clear_flag( ui_pnlStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_pnlStatus, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnWifi = lv_imgbtn_create(ui_pnlStatus);
lv_imgbtn_set_src(ui_btnWifi, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wifi_3_small_png, NULL);
lv_obj_set_width( ui_btnWifi, 16);
lv_obj_set_height( ui_btnWifi, 16);
lv_obj_set_align( ui_btnWifi, LV_ALIGN_RIGHT_MID );

ui_lblTime = lv_label_create(ui_pnlStatus);
lv_obj_set_width( ui_lblTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblTime,"23:42");

ui_btnMosquitto = lv_imgbtn_create(ui_pnlStatus);
lv_imgbtn_set_src(ui_btnMosquitto, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_mqtt_small_png, NULL);
lv_obj_set_width( ui_btnMosquitto, 24);
lv_obj_set_height( ui_btnMosquitto, 24);
lv_obj_set_x( ui_btnMosquitto, -40 );
lv_obj_set_y( ui_btnMosquitto, 0 );
lv_obj_set_align( ui_btnMosquitto, LV_ALIGN_RIGHT_MID );

ui_lblIpAddress = lv_label_create(ui_pnlStatus);
lv_obj_set_width( ui_lblIpAddress, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblIpAddress, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblIpAddress, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_lblIpAddress,"127.0.0.1");

}
